name: Deploy Django to EC2 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "/home/${{ secrets.USER }}/ot/"
          rm: false

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: >
            DEBUG,SECRET_KEY,ALLOWED_HOSTS,DB_NAME,DB_USER,DB_PASSWORD,DB_HOST,DB_PORT
          script: |
            set -e

            # Navegar al directorio del proyecto
            cd /home/${{ secrets.USER }}/ot

            # Crear archivo .env
            cat <<EOT > .env
            DEBUG=${DEBUG}
            SECRET_KEY=${SECRET_KEY}
            ALLOWED_HOSTS=${ALLOWED_HOSTS}
            DB_NAME=${DB_NAME}
            DB_USER=${DB_USER}
            DB_PASSWORD=${DB_PASSWORD}
            DB_HOST=${DB_HOST}
            DB_PORT=${DB_PORT}
            EOT

            # Actualizar e instalar paquetes nativos de Ubuntu 20.04 (Python 3.8)
            sudo apt-get update
            sudo apt-get install -y python3-venv python3-dev libmariadb-dev pkg-config gcc

            # Configurar el entorno virtual con la versión nativa (3.8)
            # Si el venv existe y no es 3.8, lo recrea
            if [ ! -f "venv/bin/python3" ]; then
              echo "Creando entorno virtual nativo..."
              rm -rf venv
              python3 -m venv venv
            fi

            # Activar e instalar dependencias
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Tareas de Django
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # Reiniciar Gunicorn
            sudo systemctl restart gunicorn

        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}